// <auto-generated />
using System;
using Clinic.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clinic.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinic.Domain.Models.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRepeated")
                        .HasColumnType("boolean");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateTime = new DateTime(2025, 10, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1L,
                            IsRepeated = false,
                            PatientId = 1L,
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = 2L,
                            DateTime = new DateTime(2025, 10, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2L,
                            IsRepeated = true,
                            PatientId = 2L,
                            RoomNumber = "102"
                        },
                        new
                        {
                            Id = 3L,
                            DateTime = new DateTime(2025, 9, 26, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3L,
                            IsRepeated = false,
                            PatientId = 3L,
                            RoomNumber = "103"
                        },
                        new
                        {
                            Id = 4L,
                            DateTime = new DateTime(2025, 9, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4L,
                            IsRepeated = true,
                            PatientId = 4L,
                            RoomNumber = "104"
                        },
                        new
                        {
                            Id = 5L,
                            DateTime = new DateTime(2025, 9, 24, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5L,
                            IsRepeated = false,
                            PatientId = 5L,
                            RoomNumber = "105"
                        },
                        new
                        {
                            Id = 6L,
                            DateTime = new DateTime(2025, 10, 26, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1L,
                            IsRepeated = true,
                            PatientId = 6L,
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = 7L,
                            DateTime = new DateTime(2025, 9, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2L,
                            IsRepeated = false,
                            PatientId = 7L,
                            RoomNumber = "102"
                        },
                        new
                        {
                            Id = 8L,
                            DateTime = new DateTime(2025, 7, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3L,
                            IsRepeated = true,
                            PatientId = 8L,
                            RoomNumber = "103"
                        },
                        new
                        {
                            Id = 9L,
                            DateTime = new DateTime(2025, 7, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4L,
                            IsRepeated = false,
                            PatientId = 9L,
                            RoomNumber = "104"
                        },
                        new
                        {
                            Id = 10L,
                            DateTime = new DateTime(2025, 8, 22, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5L,
                            IsRepeated = true,
                            PatientId = 10L,
                            RoomNumber = "105"
                        },
                        new
                        {
                            Id = 11L,
                            DateTime = new DateTime(2025, 11, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2L,
                            IsRepeated = true,
                            PatientId = 1L,
                            RoomNumber = "102"
                        },
                        new
                        {
                            Id = 12L,
                            DateTime = new DateTime(2025, 3, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3L,
                            IsRepeated = false,
                            PatientId = 2L,
                            RoomNumber = "103"
                        },
                        new
                        {
                            Id = 13L,
                            DateTime = new DateTime(2024, 9, 26, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4L,
                            IsRepeated = true,
                            PatientId = 3L,
                            RoomNumber = "104"
                        },
                        new
                        {
                            Id = 14L,
                            DateTime = new DateTime(2023, 9, 26, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5L,
                            IsRepeated = false,
                            PatientId = 4L,
                            RoomNumber = "105"
                        },
                        new
                        {
                            Id = 15L,
                            DateTime = new DateTime(2025, 4, 29, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1L,
                            IsRepeated = true,
                            PatientId = 5L,
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = 16L,
                            DateTime = new DateTime(2024, 4, 29, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6L,
                            IsRepeated = false,
                            PatientId = 11L,
                            RoomNumber = "106"
                        },
                        new
                        {
                            Id = 17L,
                            DateTime = new DateTime(2025, 11, 28, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 7L,
                            IsRepeated = true,
                            PatientId = 12L,
                            RoomNumber = "107"
                        },
                        new
                        {
                            Id = 18L,
                            DateTime = new DateTime(2025, 10, 16, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 8L,
                            IsRepeated = false,
                            PatientId = 13L,
                            RoomNumber = "108"
                        },
                        new
                        {
                            Id = 19L,
                            DateTime = new DateTime(2025, 10, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 9L,
                            IsRepeated = true,
                            PatientId = 14L,
                            RoomNumber = "109"
                        },
                        new
                        {
                            Id = 20L,
                            DateTime = new DateTime(2024, 10, 16, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 10L,
                            IsRepeated = false,
                            PatientId = 15L,
                            RoomNumber = "110"
                        },
                        new
                        {
                            Id = 21L,
                            DateTime = new DateTime(2025, 8, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 11L,
                            IsRepeated = true,
                            PatientId = 6L,
                            RoomNumber = "111"
                        },
                        new
                        {
                            Id = 22L,
                            DateTime = new DateTime(2025, 4, 17, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 12L,
                            IsRepeated = false,
                            PatientId = 7L,
                            RoomNumber = "112"
                        },
                        new
                        {
                            Id = 23L,
                            DateTime = new DateTime(2025, 11, 23, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1L,
                            IsRepeated = true,
                            PatientId = 8L,
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = 24L,
                            DateTime = new DateTime(2025, 11, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2L,
                            IsRepeated = false,
                            PatientId = 9L,
                            RoomNumber = "102"
                        },
                        new
                        {
                            Id = 25L,
                            DateTime = new DateTime(2024, 11, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3L,
                            IsRepeated = true,
                            PatientId = 10L,
                            RoomNumber = "103"
                        },
                        new
                        {
                            Id = 26L,
                            DateTime = new DateTime(2025, 10, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4L,
                            IsRepeated = false,
                            PatientId = 11L,
                            RoomNumber = "104"
                        },
                        new
                        {
                            Id = 27L,
                            DateTime = new DateTime(2025, 10, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5L,
                            IsRepeated = true,
                            PatientId = 12L,
                            RoomNumber = "105"
                        },
                        new
                        {
                            Id = 28L,
                            DateTime = new DateTime(2025, 10, 13, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6L,
                            IsRepeated = false,
                            PatientId = 13L,
                            RoomNumber = "106"
                        },
                        new
                        {
                            Id = 29L,
                            DateTime = new DateTime(2025, 10, 13, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 7L,
                            IsRepeated = true,
                            PatientId = 14L,
                            RoomNumber = "107"
                        },
                        new
                        {
                            Id = 30L,
                            DateTime = new DateTime(2024, 10, 13, 15, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 8L,
                            IsRepeated = false,
                            PatientId = 15L,
                            RoomNumber = "108"
                        });
                });

            modelBuilder.Entity("Clinic.Domain.Models.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("Experience")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("SpecializationId")
                        .HasColumnType("bigint");

                    b.Property<long>("YearOfBirth")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Experience = 15L,
                            FullName = "Смирнов Иван Петрович",
                            PassportNumber = "2121 111111",
                            SpecializationId = 1L,
                            YearOfBirth = 1970L
                        },
                        new
                        {
                            Id = 2L,
                            Experience = 8L,
                            FullName = "Кузнецова Ольга Васильевна",
                            PassportNumber = "2222 222222",
                            SpecializationId = 2L,
                            YearOfBirth = 1985L
                        },
                        new
                        {
                            Id = 3L,
                            Experience = 12L,
                            FullName = "Попов Андрей Михайлович",
                            PassportNumber = "3333 333333",
                            SpecializationId = 3L,
                            YearOfBirth = 1978L
                        },
                        new
                        {
                            Id = 4L,
                            Experience = 3L,
                            FullName = "Соколова Елена Юрьевна",
                            PassportNumber = "4444 444444",
                            SpecializationId = 4L,
                            YearOfBirth = 1992L
                        },
                        new
                        {
                            Id = 5L,
                            Experience = 20L,
                            FullName = "Морозов Дмитрий Алексеевич",
                            PassportNumber = "5555 555555",
                            SpecializationId = 5L,
                            YearOfBirth = 1965L
                        },
                        new
                        {
                            Id = 6L,
                            Experience = 10L,
                            FullName = "Васильева Ирина Сергеевна",
                            PassportNumber = "6666 666666",
                            SpecializationId = 1L,
                            YearOfBirth = 1980L
                        },
                        new
                        {
                            Id = 7L,
                            Experience = 7L,
                            FullName = "Зайцев Алексей Николаевич",
                            PassportNumber = "7777 777777",
                            SpecializationId = 2L,
                            YearOfBirth = 1987L
                        },
                        new
                        {
                            Id = 8L,
                            Experience = 18L,
                            FullName = "Денисов Сергей Владимирович",
                            PassportNumber = "8888 888888",
                            SpecializationId = 3L,
                            YearOfBirth = 1973L
                        },
                        new
                        {
                            Id = 9L,
                            Experience = 2L,
                            FullName = "Ершова Мария Павловна",
                            PassportNumber = "9999 999999",
                            SpecializationId = 4L,
                            YearOfBirth = 1995L
                        },
                        new
                        {
                            Id = 10L,
                            Experience = 14L,
                            FullName = "Ковалев Андрей Романович",
                            PassportNumber = "1010 000000",
                            SpecializationId = 5L,
                            YearOfBirth = 1976L
                        },
                        new
                        {
                            Id = 11L,
                            Experience = 9L,
                            FullName = "Иванова Екатерина Андреевна",
                            PassportNumber = "1111 000000",
                            SpecializationId = 1L,
                            YearOfBirth = 1982L
                        },
                        new
                        {
                            Id = 12L,
                            Experience = 5L,
                            FullName = "Петров Павел Петрович",
                            PassportNumber = "1212 000000",
                            SpecializationId = 2L,
                            YearOfBirth = 1990L
                        });
                });

            modelBuilder.Entity("Clinic.Domain.Models.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RhFactor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "г. Москва, ул. Тверская, д. 10",
                            BloodGroup = "A",
                            ContactPhone = "+7 (495) 123-45-67",
                            DateOfBirth = new DateOnly(1980, 1, 1),
                            FullName = "Иванов Иван Иванович",
                            Gender = "Male",
                            PassportNumber = "1111 111111",
                            RhFactor = "P"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "г. Санкт-Петербург, Невский пр., д. 20",
                            BloodGroup = "B",
                            ContactPhone = "+7 (812) 234-56-78",
                            DateOfBirth = new DateOnly(1990, 2, 2),
                            FullName = "Петров Петр Петрович",
                            Gender = "Male",
                            PassportNumber = "2222 222222",
                            RhFactor = "N"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "г. Екатеринбург, ул. Ленина, д. 30",
                            BloodGroup = "AB",
                            ContactPhone = "+7 (343) 345-67-89",
                            DateOfBirth = new DateOnly(1975, 3, 3),
                            FullName = "Сидоров Сидор Сидорович",
                            Gender = "Male",
                            PassportNumber = "3333 333333",
                            RhFactor = "P"
                        },
                        new
                        {
                            Id = 4L,
                            Address = "г. Новосибирск, Красный пр., д. 40",
                            BloodGroup = "O",
                            ContactPhone = "+7 (383) 456-78-90",
                            DateOfBirth = new DateOnly(1985, 4, 4),
                            FullName = "Смирнов Алексей Иванович",
                            Gender = "Male",
                            PassportNumber = "4444 444444",
                            RhFactor = "N"
                        },
                        new
                        {
                            Id = 5L,
                            Address = "г. Казань, ул. Баумана, д. 50",
                            BloodGroup = "A",
                            ContactPhone = "+7 (843) 567-89-01",
                            DateOfBirth = new DateOnly(1995, 5, 5),
                            FullName = "Кузнецов Дмитрий Сергеевич",
                            Gender = "Male",
                            PassportNumber = "5555 555555",
                            RhFactor = "P"
                        },
                        new
                        {
                            Id = 6L,
                            Address = "г. Нижний Новгород, ул. Большая Покровская, д. 60",
                            BloodGroup = "B",
                            ContactPhone = "+7 (831) 678-90-12",
                            DateOfBirth = new DateOnly(1970, 6, 6),
                            FullName = "Волкова Елена Андреевна",
                            Gender = "Female",
                            PassportNumber = "6666 666666",
                            RhFactor = "N"
                        },
                        new
                        {
                            Id = 7L,
                            Address = "г. Челябинск, пр. Ленина, д. 70",
                            BloodGroup = "AB",
                            ContactPhone = "+7 (351) 789-01-23",
                            DateOfBirth = new DateOnly(2000, 7, 7),
                            FullName = "Лебедева Ольга Петровна",
                            Gender = "Female",
                            PassportNumber = "7777 777777",
                            RhFactor = "P"
                        },
                        new
                        {
                            Id = 8L,
                            Address = "г. Самара, ул. Куйбышева, д. 80",
                            BloodGroup = "O",
                            ContactPhone = "+7 (846) 890-12-34",
                            DateOfBirth = new DateOnly(1982, 8, 8),
                            FullName = "Морозова Анна Владимировна",
                            Gender = "Female",
                            PassportNumber = "8888 888888",
                            RhFactor = "N"
                        },
                        new
                        {
                            Id = 9L,
                            Address = "г. Омск, ул. Ленина, д. 90",
                            BloodGroup = "A",
                            ContactPhone = "+7 (3812) 901-23-45",
                            DateOfBirth = new DateOnly(1988, 9, 9),
                            FullName = "Соколов Андрей Юрьевич",
                            Gender = "Male",
                            PassportNumber = "9999 999999",
                            RhFactor = "P"
                        },
                        new
                        {
                            Id = 10L,
                            Address = "г. Ростов-на-Дону, ул. Большая Садовая, д. 100",
                            BloodGroup = "B",
                            ContactPhone = "+7 (863) 012-34-56",
                            DateOfBirth = new DateOnly(1977, 10, 10),
                            FullName = "Васильев Сергей Михайлович",
                            Gender = "Male",
                            PassportNumber = "1010 101010",
                            RhFactor = "N"
                        },
                        new
                        {
                            Id = 11L,
                            Address = "г. Уфа, пр. Октября, д. 110",
                            BloodGroup = "AB",
                            ContactPhone = "+7 (347) 123-56-78",
                            DateOfBirth = new DateOnly(1993, 11, 11),
                            FullName = "Зайцева Ирина Николаевна",
                            Gender = "Female",
                            PassportNumber = "1111 222222",
                            RhFactor = "P"
                        },
                        new
                        {
                            Id = 12L,
                            Address = "г. Красноярск, пр. Мира, д. 120",
                            BloodGroup = "O",
                            ContactPhone = "+7 (391) 234-67-89",
                            DateOfBirth = new DateOnly(1973, 12, 12),
                            FullName = "Денисова Мария Александровна",
                            Gender = "Female",
                            PassportNumber = "1212 333333",
                            RhFactor = "N"
                        },
                        new
                        {
                            Id = 13L,
                            Address = "г. Воронеж, ул. Плехановская, д. 130",
                            BloodGroup = "A",
                            ContactPhone = "+7 (473) 345-78-90",
                            DateOfBirth = new DateOnly(1983, 1, 13),
                            FullName = "Ершов Павел Дмитриевич",
                            Gender = "Male",
                            PassportNumber = "1313 444444",
                            RhFactor = "P"
                        },
                        new
                        {
                            Id = 14L,
                            Address = "г. Пермь, Комсомольский пр., д. 140",
                            BloodGroup = "B",
                            ContactPhone = "+7 (342) 456-89-01",
                            DateOfBirth = new DateOnly(1998, 2, 14),
                            FullName = "Ковалев Роман Андреевич",
                            Gender = "Male",
                            PassportNumber = "1414 555555",
                            RhFactor = "N"
                        },
                        new
                        {
                            Id = 15L,
                            Address = "г. Волгоград, пр. Ленина, д. 150",
                            BloodGroup = "AB",
                            ContactPhone = "+7 (8442) 567-90-12",
                            DateOfBirth = new DateOnly(1979, 3, 15),
                            FullName = "Смирнова Екатерина Сергеевна",
                            Gender = "Female",
                            PassportNumber = "1515 666666",
                            RhFactor = "P"
                        });
                });

            modelBuilder.Entity("Clinic.Domain.Models.Specialization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Терапевт"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Хирург"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Кардиолог"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Невролог"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Офтальмолог"
                        });
                });

            modelBuilder.Entity("Clinic.Domain.Models.Appointment", b =>
                {
                    b.HasOne("Clinic.Domain.Models.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic.Domain.Models.Doctor", b =>
                {
                    b.HasOne("Clinic.Domain.Models.Specialization", null)
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
