namespace Clinic.Application.Dtos.RabbitMq;

/// <summary>
/// Represents a response from consumers confirming entity creation.
/// </summary>
public class EntityCreatedResponse
{
    /// <summary>
    /// Type of the created entity (e.g., "specialization", "doctor").
    /// </summary>
    public required string EntityType { get; set; }

    /// <summary>
    /// Unique identifier generated by the database for the created entity.
    /// </summary>
    public required Guid GeneratedId { get; set; }

    /// <summary>
    /// Hash of the original entity data for request-response correlation.
    /// </summary>
    public required string OriginalDataHash { get; set; }
}